### ISSUE TITLE
Add support for version constraints

### ISSUE THREAD

**Issue by cedx** [cedx/setup-hashlink#1]
It would be cool if we could use:

```yaml
- uses: cedx/setup-hashlink@v1
    with:
      version: >=1.0.0 <1.10.0 
```
