### ISSUE TITLE
krdlab/setup-haxe before cedx/setup-hashlink results in missing libneko.so.2 error, but no error when swapped

### ISSUE THREAD

**Issue by joshtynjala** [cedx/setup-hashlink#9]
If I use krdlab/setup-haxe before cedx/setup-hashlink, like this:

```yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - uses: cedx/setup-hashlink@v3
      - run: haxelib install utest --quiet
```

Then, I get the following error when I try to run the **haxelib** executable.

```
haxelib: error while loading shared libraries: libneko.so.2: cannot open shared object file: No such file or directory
Error: Process completed with exit code 127.
```

However, if I swap them, it works successfully:

```yaml
    steps:
      - uses: cedx/setup-hashlink@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - run: haxelib install utest --quiet
```

Maybe it's fine that they need to run in a specific order. I just wanted to be sure that you were aware.
